version: "3.9"
services:
  web:
    restart: always
    build: ./server/
    expose:
      - 8000
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-static:/home/billygates/server/static
    env_file: .env
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - web-static:/home/billygates/server/static
    depends_on:
      - venus

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB:  ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata:
